// embed/samples/angular/src/app/app.component.ts
import { Component, ViewChild, ElementRef, AfterViewInit } from '@angular/core'

@Component({
  selector: 'app-root',
  template: `
    <div class="sample-page">
      <h1>Angular - spo-chatbot Sample</h1>

      <div class="controls">
        <label>Token:
          <input [(ngModel)]="token" (ngModelChange)="updateToken()" type="text" placeholder="JWT token" />
        </label>
        <label>Theme:
          <select [(ngModel)]="theme" (ngModelChange)="updateTheme()">
            <option value="default">Default</option>
            <option value="bwf">BWF</option>
            <option value="bxl">BXL</option>
          </select>
        </label>
        <label>Match ID:
          <input [(ngModel)]="matchId" (ngModelChange)="updateMatchId()" type="text" placeholder="match ID" />
        </label>
      </div>

      <div class="chatbot-container">
        <spo-chatbot
          #chatbot
          api-url="http://localhost:4502"
          [attr.token]="token"
          [attr.theme]="theme"
          context-type="badminton"
          [attr.match-id]="matchId">
        </spo-chatbot>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    .sample-page {
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 24px;
      min-height: 100vh;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f5f5f5;
      color: #333;
    }
    h1 {
      font-size: 1.4rem;
      margin-bottom: 16px;
    }
    .controls {
      display: flex;
      gap: 16px;
      flex-wrap: wrap;
      align-items: center;
      margin-bottom: 20px;
      padding: 16px;
      background: #fff;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .controls label {
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 0.9rem;
      font-weight: 500;
    }
    .controls input,
    .controls select {
      padding: 6px 10px;
      border: 1px solid #d1d5db;
      border-radius: 4px;
      font-size: 0.9rem;
    }
    .controls input {
      width: 180px;
    }
    .chatbot-container {
      width: 400px;
      height: 600px;
    }
    spo-chatbot {
      display: block;
      width: 100%;
      height: 100%;
    }
  `]
})
export class AppComponent implements AfterViewInit {
  @ViewChild('chatbot') chatbotRef!: ElementRef

  token = 'dev-test-token'
  theme = 'bwf'
  matchId = 'test-match-001'

  ngAfterViewInit() {
    console.log('chatbot element:', this.chatbotRef.nativeElement.tagName)
  }

  updateToken() {
    this.chatbotRef.nativeElement.setAttribute('token', this.token)
  }

  updateTheme() {
    this.chatbotRef.nativeElement.setAttribute('theme', this.theme)
  }

  updateMatchId() {
    this.chatbotRef.nativeElement.setAttribute('match-id', this.matchId)
  }
}

// embed/samples/vue3/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'

const token = ref('dev-test-token')
const theme = ref('bwf')
const matchId = ref('test-match-001')
const chatbotRef = ref<HTMLElement | null>(null)

onMounted(() => {
  console.log('chatbot mounted:', chatbotRef.value?.tagName)
})
</script>

<template>
  <div class="sample-page">
    <h1>Vue 3 - spo-chatbot Sample</h1>

    <div class="controls">
      <label>Token:
        <input v-model="token" type="text" placeholder="JWT token" />
      </label>
      <label>Theme:
        <select v-model="theme">
          <option value="default">Default</option>
          <option value="bwf">BWF</option>
          <option value="bxl">BXL</option>
        </select>
      </label>
      <label>Match ID:
        <input v-model="matchId" type="text" placeholder="match ID" />
      </label>
    </div>

    <div class="chatbot-container">
      <spo-chatbot
        ref="chatbotRef"
        api-url="http://localhost:4502"
        :token="token"
        :theme="theme"
        context-type="badminton"
        :match-id="matchId">
      </spo-chatbot>
    </div>
  </div>
</template>

<style>
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f5f5f5;
  color: #333;
}
.sample-page {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 24px;
  min-height: 100vh;
}
h1 {
  font-size: 1.4rem;
  margin-bottom: 16px;
}
.controls {
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
  align-items: center;
  margin-bottom: 20px;
  padding: 16px;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.controls label {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.9rem;
  font-weight: 500;
}
.controls input,
.controls select {
  padding: 6px 10px;
  border: 1px solid #d1d5db;
  border-radius: 4px;
  font-size: 0.9rem;
}
.controls input {
  width: 180px;
}
.chatbot-container {
  width: 400px;
  height: 600px;
}
spo-chatbot {
  display: block;
  width: 100%;
  height: 100%;
}
</style>
